eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  application:
    name: catt-service
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/xiaxia?useSSL=false
    #username: root
    #password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:test
    dynamic:
      primary: xiaxia #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        xiaxia:
          username: root
          password: root
          #driver-class-name: com.mysql.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          #url: jdbc:mysql://localhost:3306/xiaxia?useSSL=false
          url: jdbc:p6spy:mysql://localhost:3306/xiaxia?useSSL=false
          initialSize: 5
          minIdle: 5
          maxActive: 20
        catt:
          username: root
          password: root
          #driver-class-name: com.mysql.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          #url: jdbc:mysql://localhost:3306/catt?useSSL=false
          url: jdbc:p6spy:mysql://localhost:3306/catt?useSSL=false
      initialSize: 5
      minIdle: 5
      maxActive: 20
      max-wait: 60000
#端口
server:
  port: 8001
