eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
spring:
  application:
    name: catt-service
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/xiaxia?useSSL=false
    #username: root
    #password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:mem:test
    dynamic:
      primary: xiaxia #设置默认的数据源或者数据源组,默认值即为master
      datasource:
        xiaxia:
          username: root
          password: root
          #driver-class-name: com.mysql.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          #url: jdbc:mysql://localhost:3306/xiaxia?useSSL=false
          url: jdbc:p6spy:mysql://localhost:3306/xiaxia?useSSL=false
          initialSize: 5
          minIdle: 5
          maxActive: 20
        catt:
          username: root
          password: root
          #driver-class-name: com.mysql.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          #url: jdbc:mysql://localhost:3306/catt?useSSL=false
          url: jdbc:p6spy:mysql://localhost:3306/catt?useSSL=false
      initialSize: 5
      minIdle: 5
      maxActive: 20
      max-wait: 60000
#端口
server:
  port: 8001
# Swagger相关的配置，这个要与swagger的配置类中设置一样即可，不需要说完全和我写的一样都是可以的哦!!!!
swagger:
  button-open: true
#oauth2用户认证中心
security:
  oauth2:
    resource:
      jwt:
        key-url: http:localhost:7007/oauth/token_key
        key-value: xiaxia
    client:
      client-id: client_2
      client-secret: 123456
      #获取token
      grant-type: password
      scope: server
      access-token-uri: http://localhost:7007/oauth/token
      user-authorization-uri: http://localhost:7007/oauth/authorize



